### ISSUE TITLE
`npm run build` fails

### ISSUE THREAD

**Issue by richb-hanover** [dortania/vanilla-laptop-guide#25]
Using Node 10.15.1 on macOS 10.15.4, I get an error when running `npm run build` (see output below).

`npm run test` works fine to lint and spell check the software.

What other information can I provide?

```
bash-3.2$ nvm use 10.15.1
Now using node v10.15.1 (npm v6.14.4)
bash-3.2$ npm run build
Error loading version latest: Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at evalmachine.<anonymous>:44:31
    at Object.<anonymous> (/Users/richb/.gitbook/versions/2.6.7/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

TypeError: Cannot read property 'commands' of null
bash-3.2$
```

**Comment by dhinakg** [comment]
Looks fine [here](https://travis-ci.com/github/dortania/vanilla-laptop-guide/builds/165726881), are you sure you ran `npm install`?

**Comment by richb-hanover** [comment]
I see it's working for you (and Travis CI), so that's the most important thing. I can keep linting/spell-checking, so I'm OK too. In my "spare time", I'll figure out what version mismatch is disrupting my process. Thanks.
